### ISSUE TITLE
Add preview to README.md

### ISSUE THREAD

**Issue by vini-nu** [GolDNenex/pihole-dark-purple#1]
Add images how theme looks screenshots to README.md

**Comment by GolDNenex** [comment]
That was on my todo list for a long time. Not easy to take screenshots without leaking informations.

**Comment by vini-nu** [comment]
Right click on text on Firefox and click Inspect and easily double on that text in HTML and edit to [REDACTED] or 0.00;

F12 -> Network tab -> Menubar: Throttling -> Offline to avoid constant online data changing.

---

Maybe will add photos here myself when I will sit down to PiHole so time later.
